### ISSUE TITLE
gimana kabar cuy?

### ISSUE THREAD

**Issue by asyrofist** [arifrahmanfauzi/cronbatch_alpha#1]
cuy, gimana kabar? kapan2 euy.. bikin web apps bareng yok, pake streamlit dan fastapi.. buat iseng2 aja..

**Comment by arifrahmanfauzi** [comment]
wah, iya mas.., lama gak ketemu di event bareng, boleh sih mas. Aku sekarang lagi belajar layanan AWS... deploy gitu..

**Comment by asyrofist** [comment]
> wah, iya mas.., lama gak ketemu di event bareng, boleh sih mas. Aku sekarang lagi belajar layanan AWS... deploy gitu..

btw ada gak ya, layanan serverless.. yang gak ribet macem heroku, vercel.. takutnya, lambda, ec3, masih terhitung premium.. 
sekaligus mikirin itu juga loh bro, gimana nangani kecepatan prosesnya. kalo gak pake API, pake apa ya enaknya? kalo load model dan semacamnya bisa ditaruh ke API kan enak ya, tinggal pake.. frontend gak pusing, gak mikirin algoritmanya tinggal mikirin tampilan looks nya aja..

**Comment by arifrahmanfauzi** [comment]
AWS SageMaker mas coba, aku belum pernah explore kalau deploy machine learning model, tapi di AWS ada layanannya sendiri, Lamda buat nge call aja, proses nya ada di layanan lainya, mungkin gitu mas

**Comment by asyrofist** [comment]
> AWS SageMaker mas coba, aku belum pernah explore kalau deploy machine learning model, tapi di AWS ada layanannya sendiri, Lamda buat nge call aja, proses nya ada di layanan lainya, mungkin gitu mas

btw sekarang, fokusnya backend'nya masih python.. ato php nih, hehe.. keliatannya masih seputar expert di php. Gak pengen coba beralih ke javascript.. ternyata lebih banyak lagi. kalo seputar deploy ke bahasa pemrograman itu. lumayana kenceng sih  misalnya pake vercel..

**Comment by arifrahmanfauzi** [comment]
iya mas, masih sering pakai php, laravel, python juga masih tapi jarang, javascript lagi pingin nerusin belajar lagi, mau bikin aplikasi desktop pakai electron...

**Comment by asyrofist** [comment]
> iya mas, masih sering pakai php, laravel, python juga masih tapi jarang, javascript lagi pingin nerusin belajar lagi, mau bikin aplikasi desktop pakai electron...

btw, pernah tau.. kalo dokumentasi source code, ato git enaknya dimana aja ya? sementara ini kan klao library python hanya masuk di pypi, readthedocs, ato paling banter, archieve. Punya saran, enaknya pake website/ tools apa enaknya? biar bisa dibaca orang.. kalo sekedar, di blog, kurang menarik eh, menurutku..

**Comment by arifrahmanfauzi** [comment]
kalau temenku nyaranin docusaurus mas.. aku juga lagi nyari-nyari api documentation yang bagus

**Comment by asyrofist** [comment]
> kalau temenku nyaranin docusaurus mas.. aku juga lagi nyari-nyari api documentation yang bagus

sementara ini, kalo aku bikin dokumen, ato package.. sementara dari [git](https://github.com/asyrofist/Simple-Traceability-SRS-Document) ini, ato dari [readthedocs](https://simple-tracebility.readthedocs.io/en/latest/?badge=latest) ini. Kalo semua didokumentasikan, kan lebih rapi yah.. btw sampe sekarang masih bingung.. cari cara bikin traffic naik di salah satu dokumentasi kita lumayan lama ya bro..

**Comment by arifrahmanfauzi** [comment]
tapi dokumentasi tujuanmya memang bukan traffic sih mas menurutku :D

**Comment by asyrofist** [comment]
> tapi dokumentasi tujuanmya memang bukan traffic sih mas menurutku :D

ya kalo aku sih, biar banyak lihat.. dan banyak yang pake hehe..
ya biar populer aja, kapan2 yok.. kolaborasi bareng.. pengen sekalian dibuat dan bikin papernya sekalian..  hehe..
haus akan nulis eh..

**Comment by arifrahmanfauzi** [comment]
wah paper ku aja belum publish mas :D

**Comment by asyrofist** [comment]
> wah paper ku aja belum publish mas :D

btw pake [potray](https://asyrofist.github.io/tracereq/) lumayan bagus ya..
ya meskipun ada sedikit bug, waktu deploy. kalo nama repo, src dan package di pypi gak sama
